---
title: "Tayssir paper analysis"
output: html_notebook
---
# Setup

```{r set global variables}
rm(list = ls())
NUM_TREES <- 10000
seed <- 3
set.seed(seed)
```


```{r}
source("Data set-up.R")
source("helpers.R")
```


```{r load data and packages}
library(tidyverse)
library(grf)
library(policytree)
library(mlr)
library(cowplot)
library(magrittr)
library(broom)
library(xtable)
library(haven)
library(dplyr)

morocco_cont <- read_rds('morocco2.rds')

morocco <- read_rds('morocco2.rds')

morocco_selected <- morocco %>%
  select(
    ends_with("_self"),
    matches("^a.*_1"),
    matches("^[b|f|g|h|j|k]\\d"),
    benef,
    monthly_spending,
    program_knowledge,
    schoolunitid,
    maths_results,
    group,
    hhid
         )

```


```{r define variables}
X_vars <- c('a4_1', 'a13_1', 'monthly_spending', 'a15_1_1', 'a13_self', 'a4_self', 'benef')

Y_vars <- c("maths_results")
```

```{r}
# big_covars <- morocco %>% select(-hhid, -maths_results, -group, -program_knowledge, -schoolid)
```

# Descriptive stats

```{r figure 1 maths scores hist}
morocco %>%
  ggplot(aes(x= maths_results)) +
    geom_histogram(bins = 8) +
    labs(x = "Maths results (sum of normalised components)" , y = "Count") +
    theme_classic()

ggsave("paper_outputs/figure1.png")
```

```{r maths scores by category}
maths <- read_dta("LCT Morroco/cct_aser_an.dta")

results_table <- maths %>%
  select(t6, t5_2, t4_2, t3_2) %>%
  transmute(division = t6 == 1,
            subtraction = t5_2 == 2,
            number_recog = t4_2 ==5,
            digit_recog = t3_2 == 5) %>%
  gather(key = "Indicator", "Score") %>%
  group_by(Indicator) %>%
  mutate(Indicator = factor(Indicator, level = c("digit_recog", "number_recog", "subtraction", "division"), ordered = TRUE)) %>%
  summarise(`Percent perfect` = paste0(round(mean(Score, na.rm = T) * 100,2), "%"))

results_table %>%
  xtable(caption = "Percentage of children receiving a perfect score for each category") %>%
  print(type = "latex", file="paper_outputs/table1.tex")
```

# Analysis for treatment vs control

```{r}
control_forest <- causal_forest (
  morocco_selected %>% 
    select(e1_self:monthly_spending), 
  morocco$maths_results, morocco$group_control,
  num.trees = NUM_TREES,
  clusters = morocco$schoolunitid,
  seed = seed
  )
```

```{r Just checking we aren't splitting too much on missing variables}
control_ate <- average_treatment_effect(control_forest)
control_ate
```

```{r}
qplot(x = control_forest$predictions) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = control_ate['estimate'], color = "blue") +
  scale_y_continuous(limits = c(0, 700)) +
  annotate("rect", 
           xmin = control_ate['estimate'] - (1.96 * control_ate['std.err']), 
           xmax = control_ate['estimate'] + (1.96 * control_ate['std.err']), ymin = 0, ymax = Inf,
           alpha = .1,fill = "blue") +
  ggtitle("Treatment vs control effect") + 
  labs(x = "Predictions", y = "Counts")

ggsave('paper_outputs/control_plot.png')
```


# Analysis for labelled vs conditioned

```{r fit control causal forest}
morocco <- morocco %>%
  filter(!is.na(group))

main_forest <- multi_arm_causal_forest (
  morocco %>% 
    dplyr::select(e1_self:monthly_spending) %>%
    select_if(is.numeric), 
  morocco$maths_results, morocco$group %>% as.factor(),
  # TODO: change data here
  num.trees = NUM_TREES,
  clusters = morocco$schoolunitid,
  seed = seed
  )

binary_forest <- causal_forest (
  morocco %>% 
    dplyr::select(e1_self:monthly_spending) %>%
    select_if(is.numeric), 
  morocco$maths_results, as.numeric(morocco$group != 1),
  # TODO: change data here
  num.trees = NUM_TREES,
  clusters = morocco$schoolunitid,
  seed = seed
  )
```


```{r}
main_ate <- average_treatment_effect(main_forest)
main_plots <- map(1:length(main_ate$contrast), function(x) {
  ate_est <- main_ate[x,][c("estimate", "std.err")] %>% unlist()
  preds <- main_forest$predictions[,x]
  qplot(x = preds) + 
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_vline(xintercept = ate_est['estimate'], color = "blue") +
    scale_y_continuous(limits = c(0, 800)) +
    annotate("rect", 
             xmin = ate_est['estimate'] - (1.96 * ate_est['std.err']), 
             xmax = ate_est['estimate'] + (1.96 * ate_est['std.err']), ymin = 0, ymax = Inf,
             alpha = .1,fill = "blue") +
    ggtitle("Contrast ", paste0(main_ate$contrast[x])) + 
    labs(x = "Predictions", y = "Counts")
})
save_plot('paper_outputs/figure2.png', cowplot::plot_grid(plotlist = main_plots), base_height = 5)
```


# Decision trees

```{r}
forest_results <- distilled_causal_tree(control_forest, seed = seed, replicates = 2000, num_candidate_trees = 1000, maxdepth = 3)
```

```{r}
control_results <- forest_results$estimates %>%
  mutate(est = round(est, 3), se = round(se, 3)) %>%
  arrange(as.numeric(node))

control_results
write_clip(control_results)
```

```{r}
plot_ddrct(forest_results)
```


```{r}
rpart.plot(forest_results$model)
```



# Binary conditioning analysis

```{r Just checking we aren't splitting too much on missing variables}
binary_ate <- average_treatment_effect(binary_forest)
binary_ate
```

```{r}
qplot(x = binary_forest$predictions) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = binary_ate['estimate'], color = "blue") +
  scale_y_continuous(limits = c(0, 600)) +
  annotate("rect", 
           xmin = binary_ate['estimate'] - (1.96 * binary_ate['std.err']), 
           xmax = binary_ate['estimate'] + (1.96 * binary_ate['std.err']), ymin = 0, ymax = Inf,
           alpha = .1,fill = "blue") +
  ggtitle("Labelling vs all conditioning") + 
  labs(x = "Predictions", y = "Counts")

ggsave('paper_outputs/binary_plot.png')
```

```{r exploring time use}
morocco %>%
  mutate(c_3_30_1_self = as.character(c_3_30_1_self)) %>%
  select(c_3_30_1_self) %>%
  pull() %>%
  substring(1, 1) %>%
  as.numeric() %>%
  factor(labels = c(
    "1X - Sleep / getting ready",
    "2X - Education",
    "3X - Housework",
    "4X - Gathering fuel",
    "5X - Caring",
    "6X - Family farming / production",
    "7X - Employment outside household",
    "8X - Social / recreational",
    "9X - Resting"
  )) %>%
  qplot() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("paper_outputs/time-use-values.png")
```



```{r}
binary_forest_results <- distilled_causal_tree(binary_forest, seed = seed, num_candidate_trees = 1000, replicates = 2000, maxdepth = 3)
```

```{r}
binary_results <- binary_forest_results$estimates  %>%
  mutate(est = round(est, 3), se = round(se, 3)) %>%
  arrange(as.numeric(node))

binary_results
write_clip(binary_results)
```

```{r}
plot_ddrct(binary_forest_results)
```


```{r}
het_forest_results <- distilled_causal_tree(main_forest, seed = seed, num_candidate_trees = 100, replicates = 2000, maxdepth = 3)
```

```{r}
best_treat_results <- het_forest_results[[3]]$estimates  %>%
  mutate(est = round(est, 3), se = round(se, 3)) %>%
  arrange(as.numeric(node))

best_treat_results
write_clip(best_treat_results)
```

```{r}
plot_ddrct(het_forest_results[[3]])
```

# Appendix analysis

```{r}
selected_vars <- c(
     "h1_2",
    "g11_a1_4",
    "c_3_30_1_self",
    "c_3_29_1_self",
    "c_3_18_1_self",
    "h1_16",
    "c3_troisieme_en",
    "d5_1",
    "d1_2",
    "d2_self",
    "d5_2",
    "e1_self",
    "b4_1",
    "d1_4"
)

appendix_variables <- binary_forest$X.orig[selected_vars]
```

```{r}
variable_labels <- labelled::var_label(baseline)

summary_stats <- appendix_variables %>%
  summarise(
    across(
      everything(),  # Adjust this to specify columns if not all are desired
      list(
        mean = ~ mean(.x, na.rm = TRUE),
        sd = ~ sd(.x, na.rm = TRUE),
        min = ~ min(.x, na.rm = TRUE),
        max = ~ max(.x, na.rm = TRUE),
        median = ~ median(.x, na.rm = TRUE),
        IQR = ~ IQR(.x, na.rm = TRUE)
      ),
      .names = "{.col}~{.fn}"  # Creates new column names dynamically
    )
  ) %>%
  pivot_longer(
    cols = everything(),
    names_to = c("variable", ".value"),
    names_sep = "~"
)

summary_stats %>% clipr::write_clip()
summary_stats
```

```{r}
library(scales)
library(cowplot)

plot_labs <- c(
      "How much spent last week on couscous? (dh)",
"Member 4 worked in activity 1 in last 12 months",
"Test child: Activity from 17:00 to 17:30",
"Test child: Activity from 16:30 to 17:00",
"Test child: Activity from 11:00 to 11:30",
"How much spent last week on transport to market/work? (dh)",
"Third child aged 6-15yrs present in hh",
"Child 1: Presently enrolled at school",
"Child 2 between 6-15yrs in hh",
"Test child: Member ID",
"Child 2: Presently enrolled at school",
"Test child: Amount spent since July 2007 in enrollment fee (dirhams)",
"Roof material",
"Child 4 between 6-15yrs in hh"
    ) %>% str_wrap(30)

appendix_variables[c(1,3,4,5,6,12)] %>%
  map2(
    .,
    plot_labs[c(1,3,4,5,6,12)],
    function(x, x_lab) {
      p <- ggplot(data = NULL, aes(x=x))
      if (max(x, na.rm = T) > 100) p <- p + geom_histogram()
      else p <- p + geom_bar()
      
      p + labs(title = x_lab, y = "Count", x = "") + theme_classic() + theme(plot.title = element_text(size=18))
    }
  ) %>%
  walk2(., 1:length(.), ~ggsave(paste0("appendix_plots/plot", .y, ".png"), .x))
```

```{r}
freq_tables <- appendix_variables %>%
  map(~.x %>% table %>% as.data.frame.table %>% `names<-`(c("Value", "Count")))

freq_tables
```
```{r Time use values}

tu_vars <- appendix_variables %>% select(starts_with("c_"))

bl_tu_vars <- c("c3_3_30_1", "c3_3_29_1", "c3_3_18_1")

bl_tu <- baseline[bl_tu_vars]

tu_codes <- bl_tu %>% 
  map_df(
  ~ .x %>%
  val_labels() %>% 
  as.data.frame() %>% 
  rownames_to_column("Value") %>%
  `names<-`(c("Value", "Code"))
  ) %>%
  distinct() %>%
  mutate(Code = as.character(Code))
  



tu_full <- tu_vars %>%
  map(~.x %>% table %>% as.data.frame()) %>%
  reduce(full_join, by = ".") %>%
  `names<-`(c("Code", names(tu_vars))) %>%
  mutate(Code = as.character(Code))

tu_full <- tu_full %>%
  full_join(tu_codes, by = c("Code"))

tu_full[is.na(tu_full)] <- 0

tu_full %>% clipr::write_clip()
```


```{r Time use table}
baseline$c3_3_40_1 %>% val_labels() %>% as.data.frame() 
```



